<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CRT_text_Quantity</name>
   <tag></tag>
   <elementGuidId>205768f3-b176-44cd-a18a-bbf9a3662502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;cart_quantity&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
